<?php

// Create our custom group and fields
return array(
  0 => array(
    'entity' => 'CustomGroup',
    'name' => 'constituentinfo_individual_fields',
    'update' => 'never',
    'params' => array (
      'version' => 3,
      'is_active' => 1,
      'name' => 'constituentinfo_individual_fields',
      'title' => 'Constituent Info - Individuals',
      'extends' => 'Individual',
      'style' => 'inline',
      'collapse_display' => '0',
      'is_active' => '1',
      'is_multiple' => '0',
      'collapse_adv_display' => '0',
      'is_reserved' => '0',
      'is_public' => '1',
      'api.custom_field.create' => array(
        array(
          'custom_group_id' => '$value.id',
          'label' => 'Constituent Type',
          'name' => 'constituentinfo_individual_constituent_type',
          'data_type' => 'String',
          'html_type' => 'CheckBox',
          'is_required' => '1',
          'is_searchable' => '1',
          'is_search_range' => '0',
          'weight' => '10',
          'is_active' => '1',
          'is_view' => '0',
          'options_per_line' => '2',
          'text_length' => '255',
          'note_columns' => '60',
          'note_rows' => '4',
          'in_selector' => '0'
        ),
        array(
          'custom_group_id' => '$value.id',
          'name' => 'staff_responsible',
          'name' => 'constituentinfo_staff_responsible',
          'label' => 'Staff Responsible',
          'data_type' => 'ContactReference',
          'html_type' => 'Autocomplete-Select',
          'is_searchable' => '1',
          'is_search_range' => '0',
          'weight' => '20',
          'is_active' => '1',
          'text_length' => '255',
          'note_columns' => '60',
          'note_rows' => '4',
          'filter' => 'action=lookup&group=287',
          'in_selector' => '0'
        ),
        array(
          'custom_group_id' => '$value.id',
          'label' => 'Date Started',
          'name' => 'constituentinfo_date_started',
          'data_type' => 'Date',
          'html_type' => 'Select Date',
          'is_required' => '0',
          'is_searchable' => '1',
          'is_search_range' => '1',
          'weight' => '30',
          'is_active' => '1',
          'is_view' => '0',
          'text_length' => '255',
          'start_date_years' => '30',
          'date_format' => 'mm/dd/yy',
          'note_columns' => '60',
          'note_rows' => '4',
          'in_selector' => '0'
        ),
        array(
          'custom_group_id' => '$value.id',
          'label' => 'How Started',
          'name' => 'constituentinfo_how_started',
          'data_type' => 'String',
          'html_type' => 'Select',
          'is_required' => '0',
          'is_searchable' => '1',
          'is_search_range' => '0',
          'weight' => '40',
          'help_post' => 'Describe how an individual first came to the organization.',
          'is_active' => '1',
          'is_view' => '0',
          'text_length' => '255',
          'note_columns' => '60',
          'note_rows' => '4',
          'in_selector' => '0'
        ), 
      ),
    ),
  ),
  1 => array(
    'entity' => 'CustomGroup',
    'name' => 'constituentinfo_organization_fields',
    'update' => 'never',
    'params' => array (
      'version' => 3,
      'is_active' => 1,
      'name' => 'constituentinfo_organization_fields',
      'title' => 'Constituent Info - Organization',
      'extends' => 'Organization',
      'style' => 'inline',
      'collapse_display' => '0',
      'is_active' => '1',
      'is_multiple' => '0',
      'collapse_adv_display' => '0',
      'is_reserved' => '0',
      'is_public' => '1',
      'api.custom_field.create' => array(
        array(
          'custom_group_id' => '$value.id',
          'label' => 'Constituent Type',
          'name' => 'constituentinfo_organization_constituent_type',
          'data_type' => 'String',
          'html_type' => 'CheckBox',
          'is_required' => '1',
          'is_searchable' => '1',
          'is_search_range' => '0',
          'weight' => '10',
          'is_active' => '1',
          'is_view' => '0',
          'options_per_line' => '2',
          'text_length' => '255',
          'note_columns' => '60',
          'note_rows' => '4',
          'in_selector' => '0'
        ),
      ),
    ),
  ),
  2 => array(
    'entity' => 'OptionGroup',
    'name' => 'constituentinfo_how_started_values',
    'update' => 'never',
    'params' => array (
      'version' => 3,
      'name' => 'constituentinfo_how_started_values',
      'title' => 'How Started Values',
      'is_reserved' => '1',
      'is_active' => '1',
      'is_locked' => '0',
      'api.option_value.create' => array(
        array(
          'option_group_id' => '$value.id',
          'label' => 'Meeting',
          'name' => 'constituentinfo_meeting',
          'value' => '1',
          'is_default' => '0',
          'weight' => '10',
          'is_optgroup' => '0',
          'is_reserved' => '0',
          'is_active' => '1'
        ),
        array(
          'option_group_id' => '$value.id',
          'label' => 'Event',
          'name' => 'constituentinfo_event',
          'value' => '2',
          'is_default' => '0',
          'weight' => '20',
          'is_optgroup' => '0',
          'is_reserved' => '0',
          'is_active' => '1'
        ),
        array(
          'option_group_id' => '$value.id',
          'label' => 'Phone',
          'name' => 'constituentinfo_phone',
          'value' => '3',
          'is_default' => '0',
          'weight' => '30',
          'is_optgroup' => '0',
          'is_reserved' => '0',
          'is_active' => '1'
        ),
        array(
          'option_group_id' => '$value.id',
          'label' => 'Action',
          'name' => 'constituentinfo_action',
          'value' => '4',
          'is_default' => '0',
          'weight' => '40',
          'is_optgroup' => '0',
          'is_reserved' => '0',
          'is_active' => '1'
        ),
        array(
          'option_group_id' => '$value.id',
          'label' => 'Training',
          'name' => 'constituentinfo_training',
          'value' => '5',
          'is_default' => '0',
          'weight' => '50',
          'is_optgroup' => '0',
          'is_reserved' => '0',
          'is_active' => '1'
        ),
      ),
    ),
  ),
  3 => array(
    'entity' => 'OptionGroup',
    'name' => 'constituentinfo_individual_constituent_type_values',
    'update' => 'never',
    'params' => array (
      'version' => 3,
      'name' => 'constituentinfo_individual_constituent_type_values',
      'title' => 'Individual Constituent Type Values',
      'is_reserved' => '1',
      'is_active' => '1',
      'is_locked' => '0',
      'api.option_value.create' => array(
        array(
          'option_group_id' => '$value.id',
          'label' => 'Program Participant',
          'name' => 'constituentinfo_program_participant',
          'value' => '1',
          'is_default' => '0',
          'weight' => '10',
          'is_optgroup' => '0',
          'is_reserved' => '0',
          'is_active' => '1'
        ),
        array(
          'option_group_id' => '$value.id',
          'label' => 'Non participating ally',
          'name' => 'constituentinfo_ally',
          'value' => '2',
          'is_default' => '0',
          'weight' => '20',
          'is_optgroup' => '0',
          'is_reserved' => '0',
          'is_active' => '1'
        ),
        array(
          'option_group_id' => '$value.id',
          'label' => 'Vendor',
          'name' => 'constituentinfo_vendor',
          'value' => '3',
          'is_default' => '0',
          'weight' => '30',
          'is_optgroup' => '0',
          'is_reserved' => '0',
          'is_active' => '1'
        ),
      ),
    ),
  ),
  4 => array(
    'entity' => 'OptionGroup',
    'name' => 'constituentinfo_organization_constituent_type_values',
    'update' => 'never',
    'params' => array (
      'version' => 3,
      'name' => 'constituentinfo_organization_constituent_type_values',
      'title' => 'Organization Constituent Type Values',
      'is_reserved' => '1',
      'is_active' => '1',
      'is_locked' => '0',
      'api.option_value.create' => array(
        array(
          'option_group_id' => '$value.id',
          'label' => 'Foundation',
          'name' => 'constituentinfo_foundation',
          'value' => '1',
          'is_default' => '0',
          'weight' => '10',
          'is_optgroup' => '0',
          'is_reserved' => '0',
          'is_active' => '1'
        ),
        array(
          'option_group_id' => '$value.id',
          'label' => 'Nonprofit',
          'name' => 'constituentinfo_nonprofit',
          'value' => '2',
          'is_default' => '0',
          'weight' => '20',
          'is_optgroup' => '0',
          'is_reserved' => '0',
          'is_active' => '1'
        ),
        array(
          'option_group_id' => '$value.id',
          'label' => 'Government',
          'name' => 'constituentinfo_government',
          'value' => '3',
          'is_default' => '0',
          'weight' => '30',
          'is_optgroup' => '0',
          'is_reserved' => '0',
          'is_active' => '1'
        ),
        array(
          'option_group_id' => '$value.id',
          'label' => 'Business',
          'name' => 'constituentinfo_business',
          'value' => '4',
          'is_default' => '0',
          'weight' => '40',
          'is_optgroup' => '0',
          'is_reserved' => '0',
          'is_active' => '1'
        ),
      ),
    ),
  ),
  5 => array(
    'entity' => 'Group',
    'name' => 'constituentinfo_staff',
    'update' => 'never',
    'params' => array (
      'version' => 3,
      'title' => 'Staff',
      'name' => 'constituentinfo_staff',
      'description' => "All current staff should be placed in this group.",
      'is_active' => '1',
      'visibility' => 'User and User Admin Only', 
      'is_hidden' => 0,
    ),
  ),
);
